# Generated by Django 2.1.2 on 2018-12-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testpost',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
