# Generated by Django 2.1.2 on 2018-12-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20181209_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpost',
            name='image',
            field=models.ImageField(upload_to='post'),
        ),
    ]
