# Generated by Django 2.1.2 on 2018-12-10 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20181209_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpost',
            name='image',
        ),
        migrations.AddField(
            model_name='testpost',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2018, 12, 10, 1, 22, 35, 817875), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='testpost',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
